-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema metaclothingdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `metaclothingdb` ;

-- -----------------------------------------------------
-- Schema metaclothingdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `metaclothingdb` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `metaclothingdb` ;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `isemployee` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `address` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `streetaddress` VARCHAR(100) NOT NULL,
  `city` VARCHAR(20) NOT NULL,
  `stateabbrev` VARCHAR(2) NOT NULL,
  `zip` INT(11) NOT NULL,
  `userid` INT(11) NOT NULL,
  `isbilling` TINYINT(1) NULL DEFAULT NULL,
  `isshipping` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_billingaddress` (`userid` ASC),
  CONSTRAINT `fk_billingaddress`
    FOREIGN KEY (`userid`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cart` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cart` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `userid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_cart` (`userid` ASC),
  CONSTRAINT `fk_cart`
    FOREIGN KEY (`userid`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `price` INT(11) NOT NULL,
  `brand` VARCHAR(20) NOT NULL,
  `rating` INT(11) NOT NULL,
  `category` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cartitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cartitem` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cartitem` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantity` INT(11) NOT NULL,
  `cartid` INT(11) NOT NULL,
  `itemid` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_cartitem` (`itemid` ASC),
  INDEX `idx_cartitem_0` (`cartid` ASC),
  CONSTRAINT `fk_cartitem_0`
    FOREIGN KEY (`cartid`)
    REFERENCES `cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartitem`
    FOREIGN KEY (`itemid`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sale` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sale` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `userid` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_sale` (`userid` ASC),
  CONSTRAINT `fk_sale`
    FOREIGN KEY (`userid`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `saleitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `saleitem` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `saleitem` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantity` INT(11) NOT NULL,
  `saleid` INT(11) NOT NULL,
  `itemid` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_orderitem` (`saleid` ASC),
  INDEX `idx_orderitem_0` (`itemid` ASC),
  CONSTRAINT `fk_orderitem_0`
    FOREIGN KEY (`itemid`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderitem`
    FOREIGN KEY (`saleid`)
    REFERENCES `sale` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 1, 'Shoes Sm. Male', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Tyke', 4, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 2, 'Baby Bib', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 20, 'Tyke', 3, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 3, 'Toddler Truckin T Shirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 20, 'Tyke', 2, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 4, 'Baby Crocs', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 22, 'Tyke', 4, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 5, 'My First Crossfit!', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 25, 'Tyke', 5, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 6, 'The Baby Perfect Pushup', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 22, 'Tyke', 5, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 7, 'Trains Tshirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Tyke', 2, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 8, 'Trust Fun Baby Shorts', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 22, 'Tyke', 3, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 9, 'Skechers Kids', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 15, 'Tyke', 2, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 10, 'Baby Boo Bib', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 10, 'Baby Boo', 1, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 11, 'Baby Boo Toddler Tshirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 9, 'Baby Boo', 2, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 12, 'Baby Boo Blue Shorts', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 12, 'Baby Boo', 4, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 13, 'Baby Boo Sandals', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 14, 'Baby Boo', 5, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 14, 'Banana Cabana Bandana', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 15, 'Bannana Democracy', 4, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 15, 'Banana Dew Rag', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 50, 'Bannana Democracy', 4, 'Child Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 16, 'Shoes Sm. Female', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 10, 'Tyke', 3, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 17, 'Baby Bib Pink', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 20, 'Tyke', 5, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 18, 'Toddler Princess T Shirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Tyke', 3, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 19, 'Baby Crocs', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 40, 'Tyke', 4, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 20, 'Pink I Do Girl Pushups! TShirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 50, 'Tyke', 2, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 21, 'Toddler Tiara', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 15, 'Tyke', 3, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 22, 'Princess and Dragon Tshirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 25, 'Tyke', 4, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 23, 'Khaki Capris (Minions)', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Tyke', 5, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 24, 'Skechers Kids (Female)', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 35, 'Tyke', 4, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 25, 'Baby Boo Bib Pink', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 45, 'Baby Boo', 3, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 26, 'Baby Boo Toddler Tshirt Princess', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 55, 'Baby Boo', 2, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 27, 'Baby Boo Pink Shorts', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 57, 'Baby Boo', 4, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 28, 'Baby Boo Sandals Bling Pink', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 49, 'Baby Boo', 5, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 29, 'Banana Cabana Bandana Princess', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 29, 'Banana Democracy', 5, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 30, 'Banana Dew Rag Elsa', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Banana Democracy', 2, 'Child Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 31, 'Banana Khaki Jacket', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 10, 'Banana Democracy', 3, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 32, 'Jean Shorts', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 20, 'Banana Democracy', 2, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 33, 'Soy Sauce Tshirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Banana Democracy', 1, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 34, 'Candy Tshirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 40, 'Banana Democracy', 2, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 35, 'Banana Democracy Canvas Jacket', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 50, 'Banana Democracy', 4, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 36, 'Rip Off Leather Pants', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 60, 'Rough Rider', 5, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 37, 'Heavy Duty Denim Jeans', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 15, 'Rough Rider', 4, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 38, 'Work Jacket Heavy Denim Sm.', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 25, 'Rough Rider', 4, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 39, 'Heavy Work Boots (Rubber To)', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 35, 'Rough Rider', 3, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 40, 'Heavy Duty Denim Jean Shorts', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 45, 'Rough Rider', 5, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 41, 'Heavy Duty Denim Beanie', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 55, 'Rough Rider', 3, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 42, 'Sun Records Tshirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 65, 'Carter Clothing', 4, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 43, 'Kikkoman Tshirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 75, 'Carter Clothing', 2, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 44, 'Black Med. Length Shorts', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 27, 'Carter Clothing', 3, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 45, 'Black Long Sleeve Shirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 37, 'Carter Clothing', 4, 'Juvenile Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 46, 'Hipster Halter', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 10, 'Banana Democracy', 4, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 47, 'Skit Skat Skirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 20, 'Banana Democracy', 3, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 48, 'Dramatic Dress', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Banana Democracy', 2, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 49, 'Juvenile Jumper', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 40, 'Banana Democracy', 4, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 50, 'Pillow Party PJs', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 50, 'Banana Democracy', 5, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 51, 'Chemise', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 60, 'Rough Rider', 5, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 52, 'Coolats', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 70, 'Rough Rider', 2, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 53, 'Monday Scarf', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 15, 'Rough Rider', 3, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 54, 'Tuesday Scarf', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 25, 'Rough Rider', 2, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 55, 'Wednesday Scarf', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 35, 'Rough Rider', 1, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 56, 'Thursday Scarf', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 46, 'Rough Rider', 2, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 57, 'Friday Scarf', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 57, 'Carter Clothing', 4, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 58, 'Formal Scarf', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 63, 'Carter Clothing', 5, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 59, 'Everyday Scarf', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 60, 'Carter Clothing', 4, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 60, 'Around the house Scarf', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 20, 'Carter Clothing', 4, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 61, 'Bed Time Scarf', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 13, 'Carter Clothing', 3, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 62, 'Leggings', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 20, 'Carter Clothing', 5, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 63, 'Jeggings', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 20, 'Carter Clothing', 3, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 64, 'Ugg Warmers', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Carter Clothing', 4, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 65, 'Extra Long Sweaters', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 16, 'Carter Clothing', 2, 'Juvenile Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 66, 'Red Flannel', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Carter Clothing', 3, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 67, 'Green Flannel', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 40, 'Carter Clothing', 4, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 68, 'Rainbow Flannel', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 60, 'Carter Clothing', 4, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 69, 'Utility Shemagh', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 50, 'Levi Mouse', 3, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 70, 'FTW Trucker Hat', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 102, 'Levi Mouse', 2, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 71, 'Free Tibet Trucker Hat', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 20, 'Levi Mouse', 4, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 72, 'PBR Can Slippers', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Levi Mouse', 5, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 73, 'Lightly Used Jeans', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Strauss Frock', 5, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 74, 'Never Take them off Jeans', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 50, 'Strauss Frock', 2, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 75, 'Girlfriend Jeans', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 50, 'Strauss Frock', 3, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 76, 'Rockstar Jeans', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 50, 'Strauss Frock', 2, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 77, 'Jeggings for men', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 20, 'Strauss Frock', 1, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 78, 'Ugg workboots', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 21, 'Mouse Something', 2, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 79, 'Sketchy Hoody', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 202, 'Mouse Something', 4, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 80, 'Surfer Hoody', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 10, 'Mouse Something', 5, 'Adult Male' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 81, 'Boyfriend shirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Carter Clothing', 4, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 82, 'moth eaten tshirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 40, 'Carter Clothing', 4, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 83, 'formal tank top', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 50, 'Carter Clothing', 3, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 84, 'floor length curtain skirt', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 102, 'Levi Mouse', 5, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 85, 'steam punk goggles', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 40, 'Levi Mouse', 3, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 86, 'cannot even socks', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 102, 'Levi Mouse', 4, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 87, 'afghan shawl', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 102, 'Levi Mouse', 2, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 88, '4 inch stiletto uggs', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 20, 'Strauss Frock', 3, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 89, 'ugg slippers', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Strauss Frock', 4, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 90, 'ugg converse low tops', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Strauss Frock', 4, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 91, 'thigh high socks', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 50, 'Strauss Frock', 3, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 92, 'hippy hairband', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 50, 'Strauss Frock', 2, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 93, 'vaporizor holster', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 50, 'Mouse Something', 4, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 94, 'I love ny ensemble', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 20, 'Mouse Something', 5, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 95, 'fashion specs', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 21, 'Mouse Something', 5, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 96, 'ugly cat sweater', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 202, 'Strauss Frock', 2, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 97, 'requiem for a bow tie', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 10, 'Strauss Frock', 3, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 98, 'checkered stalking cap', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 30, 'Mouse Something', 2, 'Adult Female' ); 
INSERT INTO metaclothingdb.item( id, name, description, price, brand, rating, category ) VALUES ( 99, 'ironic van gogh sweater', 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Vivamus dictum nunc nisl sit amet porttitor est convallis non. Ut commodo rutrum lacus non congue. Nullam sodales sed mi quis consectetur. Phasellus euismod mi ornare pellentesque congue. Phasellus scelerisque nisl ut venenatis facilisis. Sed ut euismod odio. Phasellus vitae eros eget augue tempus blandit in lobortis lacus.', 40, 'Mouse Something', 1, 'Adult Female' ); 

INSERT INTO metaclothingdb.`user`( id, name, email, password, isemployee ) VALUES ( 1, 'kris', 'kris@dolbeare.com', 'hello', 0 ); 
INSERT INTO metaclothingdb.`user`( id, name, email, password, isemployee ) VALUES ( 2, 'adam', 'indarys@gmail.com', 'hello', 0 ); 
INSERT INTO metaclothingdb.`user`( id, name, email, password, isemployee ) VALUES ( 3, 'erika', 'erikam@gmail.com', 'hello', 1 ); 
INSERT INTO metaclothingdb.`user`( id, name, email, password, isemployee ) VALUES ( 4, 'peter', 'pchestnut@gmail.com', 'hello', 1 ); 
INSERT INTO metaclothingdb.`user`( id, name, email, password, isemployee ) VALUES ( 5, 'michael', 'mjames@gmail.com', 'hello', 1 ); 
INSERT INTO metaclothingdb.`user`( id, name, email, password, isemployee ) VALUES ( 6, 'alexandra', 'alexandrab@gmail.com', 'hello', 1 ); 
INSERT INTO metaclothingdb.`user`( id, name, email, password, isemployee ) VALUES ( 7, 'david', 'silverfox@gmail.com', 'hello', 1 ); 


